### ISSUE TITLE
Responsive and accessible design

### ISSUE THREAD

**Issue by alice173** [alice173/TypeRacer#1]
**User story**

As a general user, I want the website to be responsive on various devices so that I can take the typing test on my preferred device.

**Acceptance Criteria:**

- [ ] The website layout adapts to different screen sizes (desktop, tablet, smartphone).

**Tasks:**

- [ ] Implement responsive design for the website to adapt to different screen sizes (desktop, tablet, smartphone)

### Start and stop actions (must-have)

**User story**

As a casual user, I want to start and stop the typing speed test so that I can accurately measure my typing speed.

**Acceptance Criteria:**

- [ ] The test begins by user action, such as clicking a start button
- [ ] The test ends by user action, such as clicking a stop button
- [ ] It is clear to the user how they can start and stop the test

**Tasks:**

- [ ] Create a user action that triggers the start of the test
- [ ] Create a user action that triggers the end of the test
- [ ] Create clear actions the user needs to take to start and stop the tes
